### ISSUE TITLE
Error on startup, Toucan 3.1.4

### ISSUE THREAD

**Issue by MrK-git** [PortableApps/Toucan#10]
Toucan crashes with the following error message on startup

![toucan_3 1 4_fehlermeldungbeimstart](https://cloud.githubusercontent.com/assets/5571081/16212539/aa01c338-3748-11e6-90a5-dbfebd1b688d.png)

**Comment by MrK-git** [comment]
sorry for german error message: libwinpthread-1.dll seems to be missing on my computer, I should reinstall the program - what of couse takes no effect.

**Comment by alex-ter** [comment]
Hmm, that's interesting and sorry for that. Too much time since last release - that forced me to install new build environment this time, including new mingw and looks like it brought in some new libraries, not used previously, which I didn't expect. Looks like I need to restore my vanilla Windows VM for testing such cases.

I'll look into this in the nearest couple of days.

**Comment by alex-ter** [comment]
@MrK-git, I've updated the 3.1.4 package, please check it out.

**Comment by alex-ter** [comment]
JFYI, my Avast suspects the packaged (i.e. .paf file, not Toucan executable itself) Toucan as "suspicious" file, which I'm pretty sure is a false positive (and VirusTotal scanner service agrees with me, though there are two "suspicious" ratings from other antiviruses out of 55).

I've reported it as a false positive to Avast using their submission form, so this hopefully will be fixed soon.

**Comment by alex-ter** [comment]
@mrk-git, have you had a chance to try it out?

**Comment by MrK-git** [comment]
@alex-ter, yes I have.

It seems to work correct now.
But in the drop down menu under "Other Commands" the print command contains unnecessary ", Message". It works with both; without ". Message" and with it... If there is no reason to specify it, it will be possibly more straight to erase it.

But it works for old scripts, too - that's the most important.

Kind regards,
Mr.K

**Comment by alex-ter** [comment]
Good, thanks for the confirmation. That Message is a message type, something, which was missing and therefore it was not working for you. I've both added it to script command template (to make it explicit, see help for other types available) and added a default value at the backend (so that old scripts could work unmodified). So it's needed, yes.
