### ISSUE TITLE
Encryption job called by script always failing

### ISSUE THREAD

**Issue by roby777** [PortableApps/Toucan#12]
Hi all,

I just discovered this app and there is something I cannot get to work.
I create a job to sync folder A over folder B; then I have created a secure job to encrypt folder A and a second job to encrypt folder B.
Finally, I have created a script via GUI to perform those three job:
--> sync A over B
--> encrypt A
--> encrypt B
but and the script finish without encrypting files inside folder A and B and the message in the progress window says that it is "impossible decrypt...." files

Am I making some mistake? It is a bug?

Thanks in advance
Roby

Windows 7 SP1
Same issue with Toucan 3.1 and 3.1.4

**Comment by alex-ter** [comment]
Hi @roby777, could you please post your script and a full log you observe, for me to understand the situation better?

**Comment by roby777** [comment]
Hi alex-ter,
[toucan_err.txt](https://github.com/PortableApps/Toucan/files/523906/toucan_err.txt)

following what I am trying to achieve.

1) I have created a Sync job named "test" to copy all files in folder crypTest into bck_crypTest
2) I have create a Secure job named t1a to encrypt all files inside folder crypTest
3) create a Secure job named t2a to encrypt all files inside folder bck_crypTest

All jobs work perfectly if launched manually from corresponding tab

Then I have used tab Script to create a job that will execute above steps:
sync([[test]])
secure([[t1a]])
secure([[t2a]])

but it fails. 

Actually I moved to English localization from Italian and secure([t1a]) will be executed while secure([t2a]) fails as in attached log

Let me know if you need more details

**Comment by alex-ter** [comment]
Looks like I cannot reproduce this on my system. It properly syncs and then encrypts files for me. There's one thing to be aware of though - when you encrypt for the first time, the original file is encrypted in-place, i.e. it's replaced with the one with the extension `.cpt`. That means the the sync job will most probably try to copy the file over again during the next run. And then the secure job will fail on that file, because it first tries to detect if there are encrypted files with the same name in this dir.

However that would result in a different error message (without ": 1" at the end). That "1" is an exit code from the `ccrypt` utility used by Toucan. That's unfortunately is quite generic to be able to say anything - could you please try encrypting those files manually with verbosity bumped up after the sync is run? The command line would be:

```
<path to your Portableapps install dir>\Toucan\App\Toucan\ccrypt.exe -v -f -e -K"yourpasswordhere" "path to file to encrypt"
```

As an alternative, you could try using Backup job for this altoghether - 7zip as the backend allows you to set password on your achives as well, so you get pretty much the same functionality + all the files are packed inside the container (archve), which can me more convenient to handle afterwards that a bunch of separate files produced by `ccrypt`.

**Comment by alex-ter** [comment]
@roby777, is this still actual?

**Comment by alex-ter** [comment]
Closing for no response
