### ISSUE TITLE
MalwarePatrol identifying Toucan as malicious

### ISSUE THREAD

**Issue by Stryder24** [PortableApps/Toucan#19]
Is this anything to be concerned about?

https://www.virustotal.com/#/url/8185ecd73e80801ed461dfb829012e42a8f171b04701a30bcf13f60eec27709a/detection

**Comment by beerisgood** [comment]
1 / 63 and only MalwarePatrol
I would say, false positiv

**Comment by JohnTHaller** [comment]
The purpose of something like VirusTotal is to make it easy to spot a false positive. The above scan showing 62 different antivirus engines saying something is clean and 1 saying otherwise confirms it's a false positive. An infected file would show [results more like this](https://www.virustotal.com/en/file/09d10ae0f763e91982e1c276aad0b26a575840ad986b8f53553a4ea0a948200f/analysis/1346055031/).

**Comment by alex-ter** [comment]
Yes, that's definitely a false postitive
